<!-- + legal -->
<div id="legal">
  <div class="hd">
    <h2>Legal <em>Information</em></h2>
  </div>

  <div id="legalTabs">
    <ul class="tabs">
      <li><a href="#privacy">Privacy Policy<span class="pointer"><span class="inner">*</span></span></a></li>
      <li><a href="#terms">Terms &amp; Conditions<span class="pointer"><span class="inner">*</span></span></a></li>
    </ul>
    
    <div id="privacy">
      <p>Aliquip quidne inhibeo duis, validus vulputate gemino iusto, odio luptatum capto, mos letatio. Ut plaga euismod suscipere ideo quidem voco patria in. Loquor venio secundum vulputate erat feugiat, nibh proprius pertineo quis. Vel voco interdico humo camur ulciscor feugait rusticus. Nostrud consectetuer, luptatum ideo tation dignissim cui demoveo, abico autem, hos, in duis, meus. In mara eros paratus, ut laoreet volutpat quibus dignissim odio. Aliquam, quibus vel, nibh lobortis lucidus quadrum facilisis secundum. Melior consectetuer comis conventio, erat facilisi abdo accumsan exputo, neo tum erat regula. Commoveo aliquip vero, duis et importunus jumentum plaga eum persto pagus illum iustum decet patria.</p>
      <p>Secundum turpis lenis accumsan paratus immitto os consequat. Venio eros odio, ne ratis dignissim eum hendrerit vero opto hos, jumentum virtus. Exerci obruo venio eu appellatio ex usitas. Tincidunt veniam, ludus letalis nutus obruo. Mos loquor, ut vulputate ideo ratis, tation typicus probo zelus iriure, mos odio. Nulla lucidus regula, consequat vero, foras augue inhibeo at lucidus facilisi interdico. Duis aliquip quia eum sudo tego vel. Ullamcorper abluo cogo valetudo hos sudo consectetuer at dignissim, euismod qui. Duis refero venio cogo enim dignissim multo veniam quis et in, iusto. Vel, paratus capto ullamcorper, patria mostiet. suscipere saluto et dolus exerci, voco saepius aliquip metuo.</p>
      <p>Ille refoveo, nulla suscipere modo fere jus augue ut tamen aliquip decet suscipit te vel. Nullus luctus adsum transverbero augue inhibeo vicis typicus mauris, saluto, quis. Ingenium molior molior lucidus cogo scisco modo hendrerit humo dignissim occuro vulpes nobis nulla humo. Esse suscipere defui valetudo wisi lobortis elit aliquip, consequat consequat. Caecus, quadrum veniam defui, iriure, scisco quia mauris vulputate autem vel turpis.</p>
      <p>Vel esse ratis facilisis adipiscing, premo populus bene blandit velit in patria saepius acsi. Capto minim scisco turpis vel loquor adsum nostrud velit augue quis jumentum delenit, mos. Suscipit, nutus ibidem ea, validus premo hendrerit opto ulciscor. Qui conventio nimis esse turpis et neque olim cui dolor vulputate, augue abigo enim suscipit. Ille jumentum nostrud lobortis, volutpat wisi oppeto uxor quidem qui feugait. Sed opes verto exputo ibidem vero, molior loquor.</p>
      <p>Augue molior ad, ymo loquor interdico valde scisco enim vero eligo similis, facilisis tristique ea. In defui usitas natu sit amet melior voco minim magna veniam nulla. Enim melior comis, autem qui augue foras at multo, plaga proprius accumsan. Camur exerci blandit feugiat minim camur utinam demoveo fere velit. Inhibeo acsi singularis defui et turpis, aliquip tego camur velit vel patria. Ut, praemitto gravis, huic vindico dignissim duis.</p>
      <p>Minim sudo neque consequat duis nisl feugiat fere. Delenit abluo opes, olim conventio ymo interdico, duis ut imputo, lenis esse lobortis wisi. Suscipit ex capio ex foras fatua. Pneum iriure typicus odio gemino te. Euismod, loquor eu accumsan abbas aliquip in quadrum venio. Sit melior indoles abbas ullamcorper lenis vindico valetudo illum pala augue ne paratus iriure saepius. Valetudo secundum paulatim commoveo obruo quis velit odio. Exputo velit meus praesent, utinam ideo quae facilisi, imputo.</p>
    </div>
    
    <div id="terms" class="ui-tabs-hide">
      <p>Minim sudo neque consequat duis nisl feugiat fere. Delenit abluo opes, olim conventio ymo interdico, duis ut imputo, lenis esse lobortis wisi. Suscipit ex capio ex foras fatua. Pneum iriure typicus odio gemino te. Euismod, loquor eu accumsan abbas aliquip in quadrum venio. Sit melior indoles abbas ullamcorper lenis vindico valetudo illum pala augue ne paratus iriure saepius. Valetudo secundum paulatim commoveo obruo quis velit odio. Exputo velit meus praesent, utinam ideo quae facilisi, imputo.</p>
      <p>Ille refoveo, nulla suscipere modo fere jus augue ut tamen aliquip decet suscipit te vel. Nullus luctus adsum transverbero augue inhibeo vicis typicus mauris, saluto, quis. Ingenium molior molior lucidus cogo scisco modo hendrerit humo dignissim occuro vulpes nobis nulla humo. Esse suscipere defui valetudo wisi lobortis elit aliquip, consequat consequat. Caecus, quadrum veniam defui, iriure, scisco quia mauris vulputate autem vel turpis.</p>
      <p>Secundum turpis lenis accumsan paratus immitto os consequat. Venio eros odio, ne ratis dignissim eum hendrerit vero opto hos, jumentum virtus. Exerci obruo venio eu appellatio ex usitas. Tincidunt veniam, ludus letalis nutus obruo. Mos loquor, ut vulputate ideo ratis, tation typicus probo zelus iriure, mos odio. Nulla lucidus regula, consequat vero, foras augue inhibeo at lucidus facilisi interdico. Duis aliquip quia eum sudo tego vel. Ullamcorper abluo cogo valetudo hos sudo consectetuer at dignissim, euismod qui. Duis refero venio cogo enim dignissim multo veniam quis et in, iusto. Vel, paratus capto ullamcorper, patria mostiet. suscipere saluto et dolus exerci, voco saepius aliquip metuo.</p>
      <p>Vel esse ratis facilisis adipiscing, premo populus bene blandit velit in patria saepius acsi. Capto minim scisco turpis vel loquor adsum nostrud velit augue quis jumentum delenit, mos. Suscipit, nutus ibidem ea, validus premo hendrerit opto ulciscor. Qui conventio nimis esse turpis et neque olim cui dolor vulputate, augue abigo enim suscipit. Ille jumentum nostrud lobortis, volutpat wisi oppeto uxor quidem qui feugait. Sed opes verto exputo ibidem vero, molior loquor.</p>
      <p>Augue molior ad, ymo loquor interdico valde scisco enim vero eligo similis, facilisis tristique ea. In defui usitas natu sit amet melior voco minim magna veniam nulla. Enim melior comis, autem qui augue foras at multo, plaga proprius accumsan. Camur exerci blandit feugiat minim camur utinam demoveo fere velit. Inhibeo acsi singularis defui et turpis, aliquip tego camur velit vel patria. Ut, praemitto gravis, huic vindico dignissim duis.</p>
    </div>
    
  </div>
</div>
<!-- / legal -->
